### ISSUE TITLE
Cannot read property 'onExpand' of undefined

### ISSUE THREAD

**Issue by indusoni** [ctrlplusb/react-sizeme#140] opened 2018-05-16 10:45 UTC
HI ,
I am using 2.4.2 version and getting following two errors
1) Uncaught TypeError: Cannot read property 'onExpand' of undefined
    at HTMLDivElement.onExpandScroll (scroll.js:397)
2) Uncaught TypeError: Cannot read property 'onShrink' of undefined
    at HTMLDivElement.onShrinkScroll (scroll.js:401)

there is one similar issue was already logged,but its status is closed.
So logging it again.

**Comment by ctrlplusb** [comment] 2018-05-17 09:18
Thanks for the report, could you please provide me with any additional details you believe may help. (e.g. details on OS and Browser, stacktrace) A simple example within https://codesandbox.io/ would be even more awesome.

I have created a base sandbox which you could fork: https://codesandbox.io/s/j2oxov8pny

Thanks!

**Comment by Hiswe** [comment] 2018-05-17 11:57
@ctrlplusb  I had also the same issue with `react-sizeme 2.4.3`

It appears for me only route-change with: 

- `react-router 4.2.0` 
- `react-router-config 1.0.0-beta.4`

although all the sizes are computed correctly before the errors are logged

![image](https://user-images.githubusercontent.com/96121/40175028-0f2a7142-5a01-11e8-8c66-1d454367ea6f.png)

Any bowser-resize or content change  after those initial errors are doing as expected

I tried to reproduce with your sandbox by just switching between 2 `sized` components  but without success :(

I hope those insight can help

n.b. this is the `element` closure variables when it errored on `onExpandScroll`

```js
{
  accessKey:""
  accessibleNode:AccessibleNode {activeDescendant: null, atomic: null, autocomplete: null, busy: null, checked: null, …}
  align:""
  assignedSlot:null
  attributeStyleMap:StylePropertyMap {size: 3}
  attributes:NamedNodeMap {0: style, style: style, length: 1}
  autocapitalize:""
  baseURI:"http://localhost:7000/"
  childElementCount:0
  childNodes:NodeList []
  children:HTMLCollection []
  classList:DOMTokenList [value: ""]
  className:""
  clientHeight:0
  clientLeft:0
  clientTop:0
  clientWidth:0
  computedName:""
  computedRole:null
  contentEditable:"inherit"
  dataset:DOMStringMap {}
  dir:""
  draggable:false
  firstChild:null
  firstElementChild:null
  hidden:false
  id:""
  inert:false
  innerHTML:""
  innerText:""
  inputMode:""
  isConnected:false
  isContentEditable:false
  lang:""
  lastChild:null
  lastElementChild:null
  localName:"div"
  namespaceURI:"http://www.w3.org/1999/xhtml"
  nextElementSibling:null
  nextSibling:null
  nodeName:"DIV"
  nodeType:1
  nodeValue:null
  nonce:""
  offsetHeight:0
  offsetLeft:0
  offsetParent:null
  offsetTop:0
  offsetWidth:0
  onabort:null
  onauxclick:null
  onbeforecopy:null
  onbeforecut:null
  onbeforepaste:null
  onblur:null
  oncancel:null
  oncanplay:null
  oncanplaythrough:null
  onchange:null
  onclick:null
  onclose:null
  oncontextmenu:null
  oncopy:null
  oncuechange:null
  oncut:null
  ondblclick:null
  ondrag:null
  ondragend:null
  ondragenter:null
  ondragleave:null
  ondragover:null
  ondragstart:null
  ondrop:null
  ondurationchange:null
  onemptied:null
  onended:null
  onerror:null
  onfocus:null
  onfullscreenchange:null
  onfullscreenerror:null
  ongotpointercapture:null
  oninput:null
  oninvalid:null
  onkeydown:null
  onkeypress:null
  onkeyup:null
  onload:null
  onloadeddata:null
  onloadedmetadata:null
  onloadstart:null
  onlostpointercapture:null
  onmousedown:null
  onmouseenter:null
  onmouseleave:null
  onmousemove:null
  onmouseout:null
  onmouseover:null
  onmouseup:null
  onmousewheel:null
  onpaste:null
  onpause:null
  onplay:null
  onplaying:null
  onpointercancel:null
  onpointerdown:null
  onpointerenter:null
  onpointerleave:null
  onpointermove:null
  onpointerout:null
  onpointerover:null
  onpointerup:null
  onprogress:null
  onratechange:null
  onreset:null
  onresize:null
  onscroll:null
  onsearch:null
  onseeked:null
  onseeking:null
  onselect:null
  onselectstart:null
  onstalled:null
  onsubmit:null
  onsuspend:null
  ontimeupdate:null
  ontoggle:null
  onvolumechange:null
  onwaiting:null
  onwebkitfullscreenchange:null
  onwebkitfullscreenerror:null
  onwheel:null
  outerHTML:"<div style="width: 100%; height: 100%; position: relative;"></div>"
  outerText:""
  ownerDocument:document
  parentElement:null
  parentNode:null
  prefix:null
  previousElementSibling:null
  previousSibling:null
  scrollHeight:0
  scrollLeft:0
  scrollTop:0
  scrollWidth:0
  shadowRoot:null
  slot:""
  spellcheck:true
  style:CSSStyleDeclaration {0: "width", 1: "height", 2: "position", alignContent: "", alignItems: "", alignSelf: "", alignmentBaseline: "", all: "", …}
  tabIndex:-1
  tagName:"DIV"
  textContent:""
  title:""
}
```

**Comment by Hiswe** [comment] 2018-05-18 02:49
Can't reproduce with `react-router` on the sandbox…

https://codesandbox.io/s/ojplrmj1l5

**Comment by k-i-m** [comment] 2018-05-22 14:11
I have the exact same issue in versions 2.4.2 and 2.4.3:

```
Uncaught TypeError: Cannot read property 'onExpand' of undefined
at HTMLDivElement.onExpandScroll (scroll.js:397)
```
```
Uncaught TypeError: Cannot read property 'onShrink' of undefined
at HTMLDivElement.onShrinkScroll (scroll.js:401)
```

Downgrade to v 2.4.1 solves the problem for now.

**Comment by Cinamonas** [comment] 2018-05-23 09:10
I’ve been seeing this, too. The actual error happens in [element-resize-detector](https://github.com/wnr/element-resize-detector)’s code.

If it’s any help, this is the stack trace:
```
scroll.js?1e50:397 Uncaught TypeError: Cannot read property 'onExpand' of undefined
    at HTMLDivElement.onExpandScroll (scroll.js?1e50:397)
  positionScrollbars @ scroll.js?1e50:268
  finalizeDomMutation @ scroll.js?1e50:583
  install @ scroll.js?1e50:595
  makeDetectable @ scroll.js?1e50:616
  attachListenerToElement @ element-resize-detector.js?0a54:229
  utils.forEach @ collection-utils.js?eb6e:14
  listenTo @ element-resize-detector.js?0a54:197
  handleDOMNode @ react-sizeme.js?e9ef:396
  componentDidMount @ react-sizeme.js?e9ef:345
```

**Comment by ctrlplusb** [comment] 2018-05-23 09:54
Thanks all for the input 👍

I have release v2.4.4 which includes some optimisations around the binding of element-resize-detector. I am hoping this may resolve the issue.

Please update and let me know if the issue persists. 👍

**Comment by bbohen** [comment] 2018-05-25 15:49
Was experiencing this issue and upgrading to v2.4.4 resolved it 👍

**Comment by ctrlplusb** [comment] 2018-05-25 15:58
Awesome, thanks for the feedback @bbohen.

I'll close this issue then. 👍

**Closed by ctrlplusb** 2018-05-25 15:58 UTC
